services:
  - type: web
    name: aethon-ai-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://aethon-ai-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: main