version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: strategic_ai
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  backend:
    build: ../backend
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg://user:pass@postgres:5432/strategic_ai
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - "8000:8000"

volumes:
  pgdata:

